### ISSUE TITLE
Synthetic ES imports are hoisted too far upward, causing issues when reflect-metadata is loaded in the same file

### ISSUE THREAD

**Issue by khusamov** [typescript-rtti/typescript-rtti#46]
> Summary: When no import location can be determined, typescript-rtti currently hoists synthetic imports to the very top of the file. But if `reflect-metadata` or other "must run first" polyfills are also in the same file, this can result in the imported code being unable to record its metadata using `Reflect.metadata`. 
>
> The issue regarding `this` appears to be due to Typescript's own emitted code, not an issue with `typescript-rtti`
> --@rezonant

Hello! Changed Parcel to Rollup. But errors still appear. The truth is already different.

I have prepared a repository so that this error can be reproduced:
https://github.com/khusamov/temp-typescript-rtti-on-rollup-errors

If you try to view the interface properties from a file, we get an empty array!

```typescript
import "reflect-metadata"
import {reflect} from 'typescript-rtti'
import IMovable from './IMovable';

// An array with two properties is expected to be output.
// But instead an empty array is output!
console.log(
	reflect<IMovable>().as('interface').reflectedInterface.properties // Output []
)
```

File `IMovable.ts`:

```typescript
export default interface IMovable {
	position: string
	readonly movementVelocity: string
}
```

If you try to read the properties of the inline-interface (without import), they are read without errors!

There are also suspicious warnings from Rollup:

```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/typescript-rtti/dist.esm/lib/reflect.js
1: var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                     ^
2:     var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
3:     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
...and 3 other occurrences

```

**Comment by rezonant** [comment]
First the easy part, the `this` message:

```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/typescript-rtti/dist.esm/lib/reflect.js
1: var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
```

That code is the code emitted by Typescript when using emitDecoratorMetadata. In this case it is looking for a global decoration helper to reduce memory usage in large applications. You can see this code emitted by vanilla Typescript in the playground: https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&target=7&module=6#code/GYVwdgxgLglg9mABMOcAUBKRBvRAnAUyhDyTQDpKBDPAcwGcsBeAPhwF9F2BuAKF4ACKdBl4QANlXr1EAIRo5+7IA

There's no issue if Rollup replaces `this` with undefined here- it will still function correctly. But it is questionable that Typescript emit this reference at all in the context of an ES module, since indeed it would always be `undefined`. Likely this is a hold over from the CommonJS version and/or previous drafts of ES modules. Might not be a bad idea to file a bug since that bit isn't doing anything.

**Comment by rezonant** [comment]
As for what's going on here, this is definitely not the previous bug, I think we should close that in favor of this one. 

Here it appears that Rollup is doing "something wrong" (TM). When the reflection metadata is being recorded, `Reflect.metadata` is undefined. Thus it never stores any of the metadata. Later, `Reflect.metadata` does get defined.

However the ordering that you are using to do the imports is correct:

```
import "reflect-metadata"
import {reflect} from 'typescript-rtti'
import IMovable from './IMovable';
```

Here, reflect-metadata polyfill should be applied first, _then_ `IMovable` should be run.

**Comment by rezonant** [comment]
Ohhhh wait no. I think I understand what's happening. Here is `index.ts` run through the transformer _without_ rollup involved:

```
const __RΦ = { m: (k, v) => (t, ...a) => t && Reflect.metadata ? Reflect.metadata(k, v)(t, ...a) : void 0, f: (f, d, n) => (d.forEach(d => d(f)), Object.defineProperty(f, "name", { value: n, writable: false }), f), c: (c, d, dp, dsp, n) => (d.forEach(d => d(c)), dp.forEach(([p, d]) => d(c.prototype, p)), dsp.forEach(([p, d]) => d(c, p)), n ? Object.defineProperty(c, "name", { value: n, writable: false }) : undefined, c), r: (o, a) => (Object.assign(o, a)), a: id => {
        let t = __RΦ.t[id];
        if (t.RΦ) {
            let r = t.RΦ;
            delete t.RΦ;
            __RΦ.r(t, r(t));
        }
        else if (t.LΦ) {
            let l = t.LΦ();
            delete t.LΦ;
            __RΦ.t[id] = t = l;
        }
        return t;
    }, t: { [83]: { LΦ: t => LΦ_0.IΦdefault } } };
import * as LΦ_0 from "./IMovable";
import "reflect-metadata";
import { reflect } from 'typescript-rtti';
// An array with two properties is expected to be output.
// But instead an empty array is output!
console.log(reflect(void 0, { TΦ: "c", t: void 0, p: [], r: void 0, tp: [__RΦ.a(83)] }).as('interface').reflectedInterface.properties);
//# sourceMappingURL=index.js.map
```

Note that we have hoisted a new `import` up to the top of the file, before `reflect-metadata` is loaded. This is definitely a `typescript-rtti` bug

**Comment by rezonant** [comment]
@khusamov In the interest of getting you going faster, try this workaround: https://github.com/khusamov/temp-typescript-rtti-on-rollup-errors/pull/1

**Comment by rezonant** [comment]
It works because it bypasses the issue where `reflect-metadata` is loaded too late, by first loading reflect-metadata outside of the module where you rely on RTTI. 

I'll work on getting this issue fixed as it will definitely be experienced in a lot more cases than rollup (basically any time you are emitting to ES modules)

**Comment by rezonant** [comment]
By the way, I was happy to see Rollup _does indeed_ do Typescript compilation _correctly_ unlike Parcel! So that's a good alternative we can recommend, though Rollup definitely won't be a drop in replacement for Parcel in all cases.

https://github.com/rollup/plugins/blob/1c3299099f2b03af0073b8c668b15251b0468b9f/packages/typescript/README.md#faster-compiling

**Comment by rezonant** [comment]
@khusamov version 0.5.4 is released which addresses this issue. Your reproduction now produces type information without the workaround.

**Comment by khusamov** [comment]
Thanks! Now it works without errors!
