### ISSUE TITLE
Incorrect properties priority

### ISSUE THREAD

**Issue by MathisTLD** [typescript-rtti/typescript-rtti#84]
using concat this way will result in parent's properties being resolved instead of child ones
I would recommend using a Map or concat ownProperties before adding parent properties

https://github.com/typescript-rtti/typescript-rtti/blob/a14745338acb48b81991273f6989c03d3c37f04b/src/lib/reflect.ts#L2292-L2293

this is an issue considering this lines:
https://github.com/typescript-rtti/typescript-rtti/blob/a14745338acb48b81991273f6989c03d3c37f04b/src/lib/reflect.ts#L2442-L2443

this should also be patched everywhere else we use concat with parent before own
like here (there are more cases in this file):
https://github.com/typescript-rtti/typescript-rtti/blob/a14745338acb48b81991273f6989c03d3c37f04b/src/lib/reflect.ts#L2137-L2138
(by the way is that normal that such things as methodNames are not ensured to be unique, because here overriding method should result in the name appearing twice i guess)

**Comment by rezonant** [comment]
Yes this is an oversight. We should take the class's ownProperty over the super's property for both properties and methods. If you want to try for a PR go for it, otherwise I can address this after we back out the changes that are blocked until Typescript 4.8 and also add support for Typescript 4.7 (#82)

**Comment by rezonant** [comment]
Let me know if you've started this, otherwise I'm hoping to tackle it today.
